version: '3.8'  # Cambié la versión a '3.8' ya que '28.2.2' no es una versión válida para Docker Compose
services:
  api:
    build: .
    container_name: fastapi_app
    networks:
      - app-network
    expose:
      - 8000

  nginx:
    image: nginx:latest
    networks:
      - app-network
    container_name: nginx_proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
   
networks:
  app-network:  # Corregido el nombre de la red
    driver: bridge